steps:
  # ===============================
  # Build Backend
  # ===============================
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--platform"
      - "linux/amd64"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/backend:$SHORT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/backend:latest"
      - "./backend"

  # ===============================
  # Build Frontend
  # ===============================
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--platform"
      - "linux/amd64"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/frontend:$SHORT_SHA"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/frontend:latest"
      - "./frontend"

  # ===============================
  # Push Images (Backend & Frontend)
  # ===============================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/backend:$SHORT_SHA",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/backend:latest",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/frontend:$SHORT_SHA",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/frontend:latest",
      ]

  # ===============================
  # Deploy Backend (With Secrets)
  # ===============================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "portfolio-backend"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/backend:$SHORT_SHA"
      - "--region"
      - "us-central1"
      # Securely injecting secrets
      - "--set-secrets"
      - "DATABASE_URL=DATABASE_URL:latest,ADMIN_PASSWORD_HASH=ADMIN_PASSWORD_HASH:latest,SECRET_KEY=SECRET_KEY:latest"
      # Non-sensitive variable
      - "--set-env-vars"
      - "ADMIN_USERNAME=sohailshaik"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"

  # ===============================
  # Deploy Frontend
  # ===============================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "portfolio-frontend"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/frontend:$SHORT_SHA"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--port"
      - "8501" # Default Streamlit port
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/backend:$SHORT_SHA"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/backend:latest"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/frontend:$SHORT_SHA"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/portfolio-repo/frontend:latest"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s"
